[package]
name = "profile"
version = "0.1.0"
include = ["Cargo.toml", "src/"]
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
countme = { version = "3.0.1", features = ["enable"] }
