[package]
name = "stdx"
version = "0.1.0"
include = ["Cargo.toml", "src/"]
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
doctest = false

[dependencies]
libc = "0.2.135"
backtrace = { version = "0.3.67", optional = true }
always-assert = { version = "0.1.2", features = ["log"] }
jod-thread = "0.1.2"
crossbeam-channel = "0.5.15"
fxhash.workspace = true
# Think twice before adding anything here

[target.'cfg(windows)'.dependencies]
miow = "0.5.0"
winapi = { version = "0.3.9", features = ["winerror"] }

[features]
# Uncomment to enable for the whole crate graph
# default = [ "backtrace" ]
