name: Deploy Docs

on:
  push:

defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm i

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build